### ISSUE TITLE
What happened to your account? 

### ISSUE THREAD

**Issue by jonasgeiler** [teganburns/Devrant-Dialogue#1]
I miss you.... :(  <3

**Comment by jonasgeiler** [comment]
You don't have to come back but at least tell us

**Comment by c3ypt1c** [comment]
I don't know who you are, but i will find you and i will bring DevRant to you xD

**Comment by teganburns** [comment]
I miss you too bby! I'll tell ya'll in an upcoming video but I'm focusing all my energy on Hyvechat right now.
